name: Deno CI
on:
  push:
    branches:
      - prod
jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    env:
      GH_ACTIONS: true
      DENO_BUILD_MODE: release
      V8_BINARY: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.x
      - name: Tests
        run: deno test --allow-read
  release:
    name: Release
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.17.0
      - name: Typescript compiler
        uses: iCrawl/action-tsc@v1
      - name: Setup package.json
        run: echo '{"main":"mod.js","name":"@sidiousware/motor_react","version":"0.0.0","publishConfig":{"access":"public"},"scripts":{"semantic-release":"semantic-release --branches prod"},"repository":{"type":"git","url":"https://github.com/sidiousvic/motor_react.git"},"author":"sidiousvic","license":"MIT","bugs":{"url":"https://github.com/sidiousvic/motor_react/issues"},"homepage":"https://github.com/sidiousvic/motor_react","devDependencies":{"semantic-release":"^17.0.4"},"release":{"branches":["prod"]}}' > package.json
      - name: Install dependencies
        run: npm install
      - name: Release
        run: cd npm && npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
